import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })


import './globals.css'


const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin']
})



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${interSans.variable} antialiased`}>{children}</body>
    </html>
  )
}
